#!/usr/bin/env python

import os
import methods

Import('env')
Import('env_modules')

env_vsdecoder_gdnative = env_modules.Clone()

env_vsdecoder_gdnative.Append(CPPPATH=['#modules/gdnative/include/'])
env_vsdecoder_gdnative.Append(CPPPATH=['#modules/gdnative/videodecoder/ffmpeg/include/'])
env_vsdecoder_gdnative.Append(LIBS = ['avformat'])
env_vsdecoder_gdnative.Append(LIBS = ['avcodec'])
env_vsdecoder_gdnative.Append(LIBS = ['avutil'])
env_vsdecoder_gdnative.Append(LIBS = ['swscale'])
env_vsdecoder_gdnative.add_source_files(env.modules_sources, '*.cpp')
